package com.example.manoa_fix_it;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

@Entity(tableName = "issue_table")
public class Issue {
    // Annotations
    @PrimaryKey(autoGenerate = true)
    private int postId;
    @ColumnInfo(name = "userId")
    private int userId;
    // Member variables represent title and details of issue
    @ColumnInfo(name = "title")
    private String title;
    @ColumnInfo(name = "loc")
    private String loc;
    @ColumnInfo(name = "status")
    private String status;
    @ColumnInfo(name = "date")
    private String date;
    @ColumnInfo(name = "desc")
    private String desc;
    @ColumnInfo(name = "points")
    private int points;
    private final int imageResource;

    /**
     * "New Issue" constructor for Issue class.
     * PostID will be autogenerated by SQLite
     * @param userId: ID of user posting
     * @param title: title of issue
     * @param loc: location of issue
     * @param status: status of issue
     * @param date: date issue was reported
     * @param desc: description of issue
     * @param points: number of likes received
     * @param imageResource: image of issue
     */
    public Issue(int userId, String title, String loc, String status, String date, String desc, int points, int imageResource) {
        this.userId = userId;
        this.title = title;
        this.loc = loc;
        this.status = status;
        this.date = date;
        this.desc = desc;
        this.points = points;
        this.imageResource = imageResource;
    }

    /**
     * "Updated Issue" constructor for Issue class.
     *  Annotated with @Ignore because the class only expects one constructor by default.
     * @param postId: post ID
     * @param userId: ID of user posting
     * @param title: title of issue
     * @param loc: location of issue
     * @param status: status of issue
     * @param date: date issue was reported
     * @param desc: description of issue
     * @param points: number of likes received
     * @param imageResource: image of issue
     */
    @Ignore
    public Issue(int postId, int userId, String title, String loc, String status, String date, String desc, int points, int imageResource) {
        this.postId = postId;
        this.userId = userId;
        this.title = title;
        this.loc = loc;
        this.status = status;
        this.date = date;
        this.desc = desc;
        this.points = points;
        this.imageResource = imageResource;
    }
    /**
     * Gets issue ID.
     * @return issue ID.
     */
    int getPostId() {
        return postId;
    }

    /**
     * Sets issue ID.
     * @param postId: issue ID.
     */
    public void setPostId(int postId) {
        this.postId = postId;
    }

    /**
     * Gets user ID.
     * @return user ID.
     */
    int getUserId() {
        return userId;
    }
    /**
     * Gets title of issue.
     * @return issue title.
     */
    String getTitle() {
        return title;
    }
    /**
     * Gets issue location.
     * @return issue details.
     */
    String getLoc() {
        return loc;
    }
    /**
     * Gets issue status.
     * @return issue details.
     */
    String getStatus() {
        return status;
    }
    /**
     * Gets issue date.
     * @return issue details.
     */
    String getDate() {
        return date;
    }
    /**
     * Gets issue details.
     * @return issue details.
     */
    String getDesc() {
        return desc;
    }
    /**
     * Gets issue details.
     * @return issue details.
     */
    int getPoints() {
        return points;
    }
    /**
     * Gets issue image header.
     * @return index of image.
     */
    public int getImageResource() {
        return imageResource;
    }
}
